# Generated by Django 3.2.9 on 2021-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=512)),
                ('isbn', models.CharField(default='', max_length=512)),
                ('authors', models.CharField(default='', max_length=512)),
                ('country', models.CharField(default='', max_length=512)),
                ('numberOfPages', models.IntegerField()),
                ('publisher', models.CharField(default='', max_length=512)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
