# Generated by Django 3.2.9 on 2021-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='authors',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='table',
            name='country',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='table',
            name='isbn',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='table',
            name='numberOfPages',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='table',
            name='publisher',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='table',
            name='release_date',
            field=models.CharField(max_length=512),
        ),
    ]
